name: Setup
description: Setup the environment for the project

runs:
  using: composite

  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun
      with:
        version: latest

    - name: Setup cache
      uses: actions/cache
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.bun }}-bun-
      
    - name: Install dependencies
      shell: bash
      run: bun install