name: Run Biome

on:
  pull_request:
  workflow_call:
    inputs:
      GH_TOKEN:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun
        with:
          bun-version: latest

      - name: Setup cache
        uses: actions/cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-
        
      - name: Install dependencies
        shell: bash
        run: bun install
  
      - name: Run format
        run: bun format

      - name: Run lint
        run: bun lint